import Header from "./ui/components/header";

import { geistMono, geistSans } from "@/app/ui/fonts";
import "./globals.css";

export const metadata = {
  title: "Pablo Teixeira",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
